## IPL 2008 to 2022 All Match Dataset

#### About this Dataset : IPL is among the most famous cricket league with players coming from worldwide. What makes this series more competitive every year is the drama with every ball and hence this dataset is a complete dataset showing match information and also data for each delivery.

##### 1.The file IPL_Matches_2008_2021.csv contains all details of the match: Venue of the match, Toss Decision, Match Winer, Man of the Match, Squads, etc.
##### 2.The file IPL_Ball_by_Ball_2008_2021.csv contains ball by ball data of each and every match: Batsman on strike, Bowler, Extras, Runs, Wicket Ball, etc.

##### Interesting Questions for Dataset:
##### 1.What is the percentage of wins of each team?
##### 2.Which venue results in a win for Batting first team and vice versa?
##### 3.Who is the most consistent batsman and bowler in each team and also in the entire league?
##### 4.Who wins the most player of the matches in the tournament?
##### 5.Predict the winning team with the consistency of wins and ball deliveries?
##### 6.Who is the most valuable player of every season?

#### Import libraries

In [1]:
import pandas as pd                    #manipulation and analysis library
import numpy as np                     #operate mathematical functions
import matplotlib.pyplot as plt        #create static, animated, and interactive visualizations.
import seaborn as sns                  #data visualization library

#### Upload Datasets

In [2]:
df_ball=pd.read_csv('IPL_Ball_by_Ball_2008_2022.csv')

In [3]:
df_ball.head()

ID  innings  overs  ballnumber       batter          bowler  \
0  1312200        1      0           1  YBK Jaiswal  Mohammed Shami   
1  1312200        1      0           2  YBK Jaiswal  Mohammed Shami   
2  1312200        1      0           3   JC Buttler  Mohammed Shami   
3  1312200        1      0           4  YBK Jaiswal  Mohammed Shami   
4  1312200        1      0           5  YBK Jaiswal  Mohammed Shami   

   non-striker extra_type  batsman_run  extras_run  total_run  non_boundary  \
0   JC Buttler        NaN            0           0          0             0   
1   JC Buttler    legbyes            0           1          1             0   
2  YBK Jaiswal        NaN            1           0          1             0   
3   JC Buttler        NaN            0           0          0             0   
4   JC Buttler        NaN            0           0          0             0   

   isWicketDelivery player_out kind fielders_involved       BattingTeam  
0                 0        NaN  NaN               NaN  Rajasthan Royals  
1                 0        NaN  NaN               NaN  Rajasthan Royals  
2                 0        NaN  NaN               NaN  Rajasthan Royals  
3                 0        NaN  NaN               NaN  Rajasthan Royals  
4                 0        NaN  NaN               NaN  Rajasthan Royals

In [4]:
df_ball.tail()

ID  innings  overs  ballnumber    batter     bowler non-striker  \
225949  335982        2     14           5   P Kumar   I Sharma    SB Joshi   
225950  335982        2     14           6  SB Joshi   I Sharma     P Kumar   
225951  335982        2     14           7   P Kumar   I Sharma    SB Joshi   
225952  335982        2     15           1  SB Joshi  LR Shukla     P Kumar   
225953  335982        2     15           2  SB Joshi  LR Shukla     P Kumar   

       extra_type  batsman_run  extras_run  total_run  non_boundary  \
225949    legbyes            0           1          1             0   
225950        NaN            1           0          1             0   
225951        NaN            0           0          0             0   
225952      wides            0           1          1             0   
225953        NaN            0           0          0             0   

        isWicketDelivery player_out    kind fielders_involved  \
225949                 0        NaN     NaN               NaN   
225950                 0        NaN     NaN               NaN   
225951                 0        NaN     NaN               NaN   
225952                 0        NaN     NaN               NaN   
225953                 1   SB Joshi  caught       BB McCullum   

                        BattingTeam  
225949  Royal Challengers Bangalore  
225950  Royal Challengers Bangalore  
225951  Royal Challengers Bangalore  
225952  Royal Challengers Bangalore  
225953  Royal Challengers Bangalore

#### Basic statistics of dataset

In [5]:
df_ball.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 225954 entries, 0 to 225953
Data columns (total 17 columns):
 #   Column             Non-Null Count   Dtype 
---  ------             --------------   ----- 
 0   ID                 225954 non-null  int64 
 1   innings            225954 non-null  int64 
 2   overs              225954 non-null  int64 
 3   ballnumber         225954 non-null  int64 
 4   batter             225954 non-null  object
 5   bowler             225954 non-null  object
 6   non-striker        225954 non-null  object
 7   extra_type         12049 non-null   object
 8   batsman_run        225954 non-null  int64 
 9   extras_run         225954 non-null  int64 
 10  total_run          225954 non-null  int64 
 11  non_boundary       225954 non-null  int64 
 12  isWicketDelivery   225954 non-null  int64 
 13  player_out         11151 non-null   object
 14  kind               11151 non-null   object
 15  fielders_involved  7988 non-null    object
 16  BattingTeam        2

In [6]:
df_ball.columns

Index(['ID', 'innings', 'overs', 'ballnumber', 'batter', 'bowler',
       'non-striker', 'extra_type', 'batsman_run', 'extras_run', 'total_run',
       'non_boundary', 'isWicketDelivery', 'player_out', 'kind',
       'fielders_involved', 'BattingTeam'],
      dtype='object')

In [7]:
df_ball.axes

[RangeIndex(start=0, stop=225954, step=1),
 Index(['ID', 'innings', 'overs', 'ballnumber', 'batter', 'bowler',
        'non-striker', 'extra_type', 'batsman_run', 'extras_run', 'total_run',
        'non_boundary', 'isWicketDelivery', 'player_out', 'kind',
        'fielders_involved', 'BattingTeam'],
       dtype='object')]

In [8]:
df_ball.ndim

2

In [9]:
df_ball.size

3841218

In [10]:
df_ball.shape

(225954, 17)

In [11]:
df_ball[df_ball.duplicated()].shape  #used to find and count duplicate rows in the df_ball dataframe.

(0, 17)

In [12]:
df_ball.values

array([[1312200, 1, 0, ..., nan, nan, 'Rajasthan Royals'],
       [1312200, 1, 0, ..., nan, nan, 'Rajasthan Royals'],
       [1312200, 1, 0, ..., nan, nan, 'Rajasthan Royals'],
       ...,
       [335982, 2, 14, ..., nan, nan, 'Royal Challengers Bangalore'],
       [335982, 2, 15, ..., nan, nan, 'Royal Challengers Bangalore'],
       [335982, 2, 15, ..., 'caught', 'BB McCullum',
        'Royal Challengers Bangalore']], dtype=object)

In [13]:
#Check for Missing Values
missing_values = df_ball.isnull().sum()
print(missing_values)

ID                        0
innings                   0
overs                     0
ballnumber                0
batter                    0
bowler                    0
non-striker               0
extra_type           213905
batsman_run               0
extras_run                0
total_run                 0
non_boundary              0
isWicketDelivery          0
player_out           214803
kind                 214803
fielders_involved    217966
BattingTeam               0
dtype: int64


In [14]:
#fill missing value for categorical columns
df_ball['extra_type'] = df_ball['extra_type'].fillna(df_ball['extra_type'].mode().iloc[0])
df_ball['player_out'] = df_ball['player_out'].fillna(df_ball['player_out'].mode().iloc[0])
df_ball['kind'] = df_ball['kind'].fillna(df_ball['kind'].mode().iloc[0])
df_ball['fielders_involved'] = df_ball['fielders_involved'].fillna(df_ball['fielders_involved'].mode().iloc[0])

In [15]:
df_ball.values

array([[1312200, 1, 0, ..., 'caught', 'MS Dhoni', 'Rajasthan Royals'],
       [1312200, 1, 0, ..., 'caught', 'MS Dhoni', 'Rajasthan Royals'],
       [1312200, 1, 0, ..., 'caught', 'MS Dhoni', 'Rajasthan Royals'],
       ...,
       [335982, 2, 14, ..., 'caught', 'MS Dhoni',
        'Royal Challengers Bangalore'],
       [335982, 2, 15, ..., 'caught', 'MS Dhoni',
        'Royal Challengers Bangalore'],
       [335982, 2, 15, ..., 'caught', 'BB McCullum',
        'Royal Challengers Bangalore']], dtype=object)

In [16]:
#Verify Missing Values
missing_values = df_ball[['extra_type','player_out','kind','fielders_involved']].isnull().sum()
print(missing_values)

extra_type           0
player_out           0
kind                 0
fielders_involved    0
dtype: int64


In [17]:
df_ball.values

array([[1312200, 1, 0, ..., 'caught', 'MS Dhoni', 'Rajasthan Royals'],
       [1312200, 1, 0, ..., 'caught', 'MS Dhoni', 'Rajasthan Royals'],
       [1312200, 1, 0, ..., 'caught', 'MS Dhoni', 'Rajasthan Royals'],
       ...,
       [335982, 2, 14, ..., 'caught', 'MS Dhoni',
        'Royal Challengers Bangalore'],
       [335982, 2, 15, ..., 'caught', 'MS Dhoni',
        'Royal Challengers Bangalore'],
       [335982, 2, 15, ..., 'caught', 'BB McCullum',
        'Royal Challengers Bangalore']], dtype=object)

In [18]:
df_ball.describe()

ID        innings          overs     ballnumber  \
count  2.259540e+05  225954.000000  225954.000000  225954.000000   
mean   8.320470e+05       1.483868       9.185679       3.619750   
std    3.379542e+05       0.503104       5.681797       1.810633   
min    3.359820e+05       1.000000       0.000000       1.000000   
25%    5.012620e+05       1.000000       4.000000       2.000000   
50%    8.297370e+05       1.000000       9.000000       4.000000   
75%    1.178395e+06       2.000000      14.000000       5.000000   
max    1.312200e+06       6.000000      19.000000      10.000000   

         batsman_run     extras_run     total_run   non_boundary  \
count  225954.000000  225954.000000  225954.00000  225954.000000   
mean        1.243523       0.066907       1.31043       0.000093   
std         1.618166       0.341470       1.60605       0.009640   
min         0.000000       0.000000       0.00000       0.000000   
25%         0.000000       0.000000       0.00000       0.000000   
50%         1.000000       0.000000       1.00000       0.000000   
75%         1.000000       0.000000       1.00000       0.000000   
max         6.000000       7.000000       7.00000       1.000000   

       isWicketDelivery  
count     225954.000000  
mean           0.049351  
std            0.216600  
min            0.000000  
25%            0.000000  
50%            0.000000  
75%            0.000000  
max            1.000000

In [19]:
df_ball.sample()

ID  innings  overs  ballnumber     batter    bowler non-striker  \
116396  829709        1      5           1  SPD Smith  AR Patel     KK Nair   

       extra_type  batsman_run  extras_run  total_run  non_boundary  \
116396      wides            4           0          4             0   

        isWicketDelivery player_out    kind fielders_involved  \
116396                 0  RG Sharma  caught          MS Dhoni   

             BattingTeam  
116396  Rajasthan Royals

In [20]:
df_ball.std()   #1

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_270436\1943882932.py:1: FutureWarning: The default value of numeric_only in DataFrame.std is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_ball.std()   #1


ID                  337954.245970
innings                  0.503104
overs                    5.681797
ballnumber               1.810633
batsman_run              1.618166
extras_run               0.341470
total_run                1.606050
non_boundary             0.009640
isWicketDelivery         0.216600
dtype: float64

In [21]:
std_deviation = df_ball.std() #2
print(std_deviation)

ID                  337954.245970
innings                  0.503104
overs                    5.681797
ballnumber               1.810633
batsman_run              1.618166
extras_run               0.341470
total_run                1.606050
non_boundary             0.009640
isWicketDelivery         0.216600
dtype: float64


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_270436\1427261579.py:1: FutureWarning: The default value of numeric_only in DataFrame.std is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  std_deviation = df_ball.std() #2


In [22]:
df_ball.head()

ID  innings  overs  ballnumber       batter          bowler  \
0  1312200        1      0           1  YBK Jaiswal  Mohammed Shami   
1  1312200        1      0           2  YBK Jaiswal  Mohammed Shami   
2  1312200        1      0           3   JC Buttler  Mohammed Shami   
3  1312200        1      0           4  YBK Jaiswal  Mohammed Shami   
4  1312200        1      0           5  YBK Jaiswal  Mohammed Shami   

   non-striker extra_type  batsman_run  extras_run  total_run  non_boundary  \
0   JC Buttler      wides            0           0          0             0   
1   JC Buttler    legbyes            0           1          1             0   
2  YBK Jaiswal      wides            1           0          1             0   
3   JC Buttler      wides            0           0          0             0   
4   JC Buttler      wides            0           0          0             0   

   isWicketDelivery player_out    kind fielders_involved       BattingTeam  
0                 0  RG Sharma  caught          MS Dhoni  Rajasthan Royals  
1                 0  RG Sharma  caught          MS Dhoni  Rajasthan Royals  
2                 0  RG Sharma  caught          MS Dhoni  Rajasthan Royals  
3                 0  RG Sharma  caught          MS Dhoni  Rajasthan Royals  
4                 0  RG Sharma  caught          MS Dhoni  Rajasthan Royals

In [23]:
df_ball['total_run'].describe()

count    225954.00000
mean          1.31043
std           1.60605
min           0.00000
25%           0.00000
50%           1.00000
75%           1.00000
max           7.00000
Name: total_run, dtype: float64

In [24]:
df_ball['batsman_run'].describe()

count    225954.000000
mean          1.243523
std           1.618166
min           0.000000
25%           0.000000
50%           1.000000
75%           1.000000
max           6.000000
Name: batsman_run, dtype: float64

#### Upload Second file of dataset.

In [25]:
df_matches=pd.read_csv('IPL_Matches_2008_2022.csv')

In [26]:
df_matches.head()

ID       City        Date Season  MatchNumber  \
0  1312200  Ahmedabad  2022-05-29   2022        Final   
1  1312199  Ahmedabad  2022-05-27   2022  Qualifier 2   
2  1312198    Kolkata  2022-05-25   2022   Eliminator   
3  1312197    Kolkata  2022-05-24   2022  Qualifier 1   
4  1304116     Mumbai  2022-05-22   2022           70   

                         Team1                 Team2  \
0             Rajasthan Royals        Gujarat Titans   
1  Royal Challengers Bangalore      Rajasthan Royals   
2  Royal Challengers Bangalore  Lucknow Super Giants   
3             Rajasthan Royals        Gujarat Titans   
4          Sunrisers Hyderabad          Punjab Kings   

                              Venue            TossWinner TossDecision  \
0  Narendra Modi Stadium, Ahmedabad      Rajasthan Royals          bat   
1  Narendra Modi Stadium, Ahmedabad      Rajasthan Royals        field   
2             Eden Gardens, Kolkata  Lucknow Super Giants        field   
3             Eden Gardens, Kolkata        Gujarat Titans        field   
4          Wankhede Stadium, Mumbai   Sunrisers Hyderabad          bat   

  SuperOver                  WinningTeam    WonBy  Margin method  \
0         N               Gujarat Titans  Wickets     7.0    NaN   
1         N             Rajasthan Royals  Wickets     7.0    NaN   
2         N  Royal Challengers Bangalore     Runs    14.0    NaN   
3         N               Gujarat Titans  Wickets     7.0    NaN   
4         N                 Punjab Kings  Wickets     5.0    NaN   

  Player_of_Match                                       Team1Players  \
0       HH Pandya  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...   
1      JC Buttler  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...   
2      RM Patidar  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...   
3       DA Miller  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...   
4   Harpreet Brar  ['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...   

                                        Team2Players        Umpire1  \
0  ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...    CB Gaffaney   
1  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...    CB Gaffaney   
2  ['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...  J Madanagopal   
3  ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...   BNJ Oxenford   
4  ['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...   AK Chaudhary   

         Umpire2  
0    Nitin Menon  
1    Nitin Menon  
2       MA Gough  
3      VK Sharma  
4  NA Patwardhan

In [27]:
df_matches.info()   #used to display a concise summary of the information about a DataFrame.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   ID               950 non-null    int64  
 1   City             899 non-null    object 
 2   Date             950 non-null    object 
 3   Season           950 non-null    object 
 4   MatchNumber      950 non-null    object 
 5   Team1            950 non-null    object 
 6   Team2            950 non-null    object 
 7   Venue            950 non-null    object 
 8   TossWinner       950 non-null    object 
 9   TossDecision     950 non-null    object 
 10  SuperOver        946 non-null    object 
 11  WinningTeam      946 non-null    object 
 12  WonBy            950 non-null    object 
 13  Margin           932 non-null    float64
 14  method           19 non-null     object 
 15  Player_of_Match  946 non-null    object 
 16  Team1Players     950 non-null    object 
 17  Team2Players    

In [28]:
#1 Check for Missing Values
missing_values = df_matches.isnull().sum()
print(missing_values)

ID                   0
City                51
Date                 0
Season               0
MatchNumber          0
Team1                0
Team2                0
Venue                0
TossWinner           0
TossDecision         0
SuperOver            4
WinningTeam          4
WonBy                0
Margin              18
method             931
Player_of_Match      4
Team1Players         0
Team2Players         0
Umpire1              0
Umpire2              0
dtype: int64


In [29]:
#2 checking null values 
df_matches.isnull().sum()

ID                   0
City                51
Date                 0
Season               0
MatchNumber          0
Team1                0
Team2                0
Venue                0
TossWinner           0
TossDecision         0
SuperOver            4
WinningTeam          4
WonBy                0
Margin              18
method             931
Player_of_Match      4
Team1Players         0
Team2Players         0
Umpire1              0
Umpire2              0
dtype: int64

In [30]:
#fill missing value for categorical columns
df_matches['City'] = df_matches['City'].fillna(df_matches['City'].mode().iloc[0])
df_matches['Margin'] = df_matches['Margin'].fillna(0.0)
df_matches['method'] = df_matches['method'].fillna(df_matches['method'].mode().iloc[0])

In [31]:
df_matches.values    #used to obtain the values of a DataFrame.

array([[1312200, 'Ahmedabad', '2022-05-29', ...,
        "['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pandya', 'DA Miller', 'R Tewatia', 'Rashid Khan', 'R Sai Kishore', 'LH Ferguson', 'Yash Dayal', 'Mohammed Shami']",
        'CB Gaffaney', 'Nitin Menon'],
       [1312199, 'Ahmedabad', '2022-05-27', ...,
        "['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D Padikkal', 'SO Hetmyer', 'R Parag', 'R Ashwin', 'TA Boult', 'YS Chahal', 'M Prasidh Krishna', 'OC McCoy']",
        'CB Gaffaney', 'Nitin Menon'],
       [1312198, 'Kolkata', '2022-05-25', ...,
        "['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda', 'MP Stoinis', 'E Lewis', 'KH Pandya', 'PVD Chameera', 'Mohsin Khan', 'Avesh Khan', 'Ravi Bishnoi']",
        'J Madanagopal', 'MA Gough'],
       ...,
       [335984, 'Delhi', '2008-04-19', ...,
        "['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif', 'DS Lehmann', 'RA Jadeja', 'M Rawat', 'D Salunkhe', 'SK Warne', 'SK Trivedi', 'MM Patel']",
        'Aleem Dar', 'GA Pratapkumar'],
    

In [32]:
#Verify Missing Values
missing_values = df_matches[['City','Margin','method']].isnull().sum()  #.isnull() is used to check for missing values in the selected columns.
print(missing_values)

City      0
Margin    0
method    0
dtype: int64


In [33]:
df_matches.describe()     #generate a summary of descriptive statistics for the numeric columns in a DataFrame.

ID      Margin
count  9.500000e+02  950.000000
mean   8.304852e+05   16.733684
std    3.375678e+05   21.552925
min    3.359820e+05    0.000000
25%    5.012612e+05    5.000000
50%    8.297380e+05    8.000000
75%    1.175372e+06   18.000000
max    1.312200e+06  146.000000

In [34]:
df_matches.columns #used to obtain the column names of a DataFrame

Index(['ID', 'City', 'Date', 'Season', 'MatchNumber', 'Team1', 'Team2',
       'Venue', 'TossWinner', 'TossDecision', 'SuperOver', 'WinningTeam',
       'WonBy', 'Margin', 'method', 'Player_of_Match', 'Team1Players',
       'Team2Players', 'Umpire1', 'Umpire2'],
      dtype='object')

In [35]:
df_matches.axes     #attribute in a DataFrame provides information about the row and column labels / index.

[RangeIndex(start=0, stop=950, step=1),
 Index(['ID', 'City', 'Date', 'Season', 'MatchNumber', 'Team1', 'Team2',
        'Venue', 'TossWinner', 'TossDecision', 'SuperOver', 'WinningTeam',
        'WonBy', 'Margin', 'method', 'Player_of_Match', 'Team1Players',
        'Team2Players', 'Umpire1', 'Umpire2'],
       dtype='object')]

In [36]:
df_matches.ndim   #used to determine the number of dimensions in a DataFrame.

2

In [37]:
df_matches.size   #used to determine the total number of elements in a DataFrame.

19000

In [38]:
df_matches.shape   #obtain the dimensions of a DataFrame.

(950, 20)

In [39]:
df_matches[df_matches.duplicated()].shape   #find and count the duplicate rows in a DataFrame

(0, 20)

In [40]:
df_matches.values  #obtain the values of a DataFrame

array([[1312200, 'Ahmedabad', '2022-05-29', ...,
        "['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pandya', 'DA Miller', 'R Tewatia', 'Rashid Khan', 'R Sai Kishore', 'LH Ferguson', 'Yash Dayal', 'Mohammed Shami']",
        'CB Gaffaney', 'Nitin Menon'],
       [1312199, 'Ahmedabad', '2022-05-27', ...,
        "['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D Padikkal', 'SO Hetmyer', 'R Parag', 'R Ashwin', 'TA Boult', 'YS Chahal', 'M Prasidh Krishna', 'OC McCoy']",
        'CB Gaffaney', 'Nitin Menon'],
       [1312198, 'Kolkata', '2022-05-25', ...,
        "['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda', 'MP Stoinis', 'E Lewis', 'KH Pandya', 'PVD Chameera', 'Mohsin Khan', 'Avesh Khan', 'Ravi Bishnoi']",
        'J Madanagopal', 'MA Gough'],
       ...,
       [335984, 'Delhi', '2008-04-19', ...,
        "['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif', 'DS Lehmann', 'RA Jadeja', 'M Rawat', 'D Salunkhe', 'SK Warne', 'SK Trivedi', 'MM Patel']",
        'Aleem Dar', 'GA Pratapkumar'],
    

In [41]:
df_matches.sample()  #obtain a random sample from a DataFrame.

ID    City        Date Season MatchNumber           Team1  \
613  598011  Mumbai  2013-04-13   2013          15  Mumbai Indians   

             Team2             Venue      TossWinner TossDecision SuperOver  \
613  Pune Warriors  Wankhede Stadium  Mumbai Indians          bat         N   

        WinningTeam WonBy  Margin method Player_of_Match  \
613  Mumbai Indians  Runs    41.0    D/L       RG Sharma   

                                          Team1Players  \
613  ['RT Ponting', 'SR Tendulkar', 'KD Karthik', '...   

                                          Team2Players Umpire1     Umpire2  
613  ['AJ Finch', 'RV Uthappa', 'LRPL Taylor', 'Yuv...  S Ravi  SJA Taufel

In [42]:
df_matches.std()   # calculating the standard deviation of a DataFrame.

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_270436\2765350072.py:1: FutureWarning: The default value of numeric_only in DataFrame.std is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_matches.std()   # calculating the standard deviation of a DataFrame.


ID        337567.829494
Margin        21.552925
dtype: float64